FROM ghcr.io/edera-dev/cross-base-linux-musl:latest@sha256:a591bb18a5ede06c6e814a4d263dddb172e0b9f998873841163585c286484983 AS build

ENV TARGET_LIBC=musl TARGET_VENDOR=unknown DISABLE_CROSS_RS=1

WORKDIR /usr/src/app
COPY . .
RUN ./hack/build/cargo.sh build --release --bin edera-check
RUN mv ./target/$(./hack/build/target.sh)/release/edera-check /usr/sbin

FROM cgr.dev/chainguard/wolfi-base:latest
ENTRYPOINT ["/usr/sbin/edera-check"]
COPY --from=build /usr/sbin/edera-check /usr/sbin/edera-check
