FROM ghcr.io/edera-dev/cross-base-linux-musl:latest@sha256:35c5a25a1f513812bf334a78aa6e37a2f154bfcd28e2dd7f1f90c2bcde69f6f3 AS build

ENV TARGET_LIBC=musl TARGET_VENDOR=unknown DISABLE_CROSS_RS=1

WORKDIR /usr/src/app
COPY . .
RUN ./hack/build/cargo.sh build --release --bin edera-check
RUN mv ./target/$(./hack/build/target.sh)/release/edera-check /usr/sbin

FROM cgr.dev/chainguard/wolfi-base:latest
ENTRYPOINT ["/usr/sbin/edera-check"]
COPY --from=build /usr/sbin/edera-check /usr/sbin/edera-check
