FROM ghcr.io/edera-dev/cross-base-linux-musl:latest@sha256:017a17f5322799fdfcb391d5ffd838927cd4c8dea8f1195e58a368a8e6b48556 AS build

ENV TARGET_LIBC=musl TARGET_VENDOR=unknown DISABLE_CROSS_RS=1

WORKDIR /usr/src/app
COPY . .
RUN ./hack/build/cargo.sh build --release --bin edera-check
RUN mv ./target/$(./hack/build/target.sh)/release/edera-check /usr/sbin

FROM cgr.dev/chainguard/wolfi-base:latest
ENTRYPOINT ["/usr/sbin/edera-check"]
COPY --from=build /usr/sbin/edera-check /usr/sbin/edera-check
