name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # Weekly
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write # to push the updates
      pull-requests: write # to open Pull requests
      id-token: write # used to sign the commits using gitsign

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.2.0
      with:
        persist-credentials: false

    - name: generate cultivator token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: generate-token
      with:
        app-id: "${{ secrets.EDERA_CULTIVATION_APP_ID }}"
        private-key: "${{ secrets.EDERA_CULTIVATION_APP_PRIVATE_KEY }}"

    - uses: chainguard-dev/digestabot@33d0b78e580aa0c83fe188eb3dfad6611b662479 # a110b65f3d4742d56b5b2b2306de6e2e54306724
      with:
        token: "${{ steps.generate-token.outputs.token }}"
        signoff: true
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        labels-for-pr: automated pr, kind/cleanup
        branch-for-pr: update-digests
        title-for-pr: Update images digests
        description-for-pr: Update images digests
        commit-message: Update images digests
        use-gitsign: false
        include-files: '*.yaml,*.yml,Dockerfile*,Containerfile*,Cross.toml,Makefile*,*.sh,*.tf,*.tfvars'
