name: Markdown Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  markdownlint:
    name: runner / markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: generate cultivator token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: generate-token
        with:
          app-id: "${{ secrets.EDERA_CULTIVATION_APP_ID }}"
          private-key: "${{ secrets.EDERA_CULTIVATION_APP_PRIVATE_KEY }}"

      - name: markdownlint
        uses: step-security/action-markdownlint@7c5273c5bd9d67d29ea1d2b0974c26b994595be7
        with:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          reporter: github-pr-review
          level: warning
          fail_level: error
          markdownlint_flags: '--config .markdownlint.json .'
        continue-on-error: false

